### ISSUE TITLE
sorry we broke your interface since we simplified the C interface!

### ISSUE THREAD

**Issue by ahbarnett** [ludvigak/FINUFFT.jl#1]
Dear Ludvig,
Sorry, I now see you built the jl interface around the C interface. From our end it has been good to simplify the C calling sequences to be identical to the C++ ones. (as of v 1.1). The C interface was really clunky. Now we call the C++ directly; much better.
But this means you'll have to fix your julia wrapper - mostly removing _c from things and passing opts as pointer.

Although I'm trying to play with julia (struggling over getting fast loops on unrelated project), I think you'd be much faster at tweaking your code.
Let me know if I can help.
Best, Alex

**Comment by ludvigak** [comment]
No problem. The interface downloads and builds the source for the v1.0 release, so nothing is broken yet. Once you release a new version, I will update the interface to use that, which is a simple fix.

**Comment by ludvigak** [comment]
Fixed in v0.4.0
