### ISSUE TITLE
build on osx

### ISSUE THREAD

**Issue by pnavaro** [ludvigak/FINUFFT.jl#2]
Thanks for this work. I wanted to use your library and I try to build it on macOS.
My first move was to make a change in deps/build.jl
~~~
-buildcmd = `make lib LIBRARY_PATH=$lib CPATH=$inc`
+buildcmd = `make lib LIBRARY_PATH=$lib CPATH=$inc CXX=g++-8 CC=gcc-8`
~~~

It generates a .so library file but a dylib seems to be expected...

~~~
ERROR: LoadError: failed process: Process(`cp /Users/navaro/.julia/packages/FINUFFT/W7sdX/deps/src/finufft-1.0/lib/libfinufft.dylib /Users/navaro/.julia/packages/FINUFFT/W7sdX/deps/usr/lib/libfinufft.dylib`, ProcessExited(1)) [1]
~~~

If you have an idea...

**Comment by ludvigak** [comment]
Hi! It's great if you're interested in trying this out on a Mac, since I don't have access to one myself.

The name of the library file that the build script tries to copy comes from this line:

https://github.com/ludvigak/FINUFFT.jl/blob/9fabc17af99d3708df4887b31ed6377c004f4aa5/deps/build.jl#L40

Try changing that to 
```
libname = "libfinufft.so"
```
Since the build appears to be successful, this could hopefully be enough to get everything runing.

**Comment by pnavaro** [comment]
I made this change in build.jl and it works well if you have gcc installed with homebrew on Mac
```
if Sys.KERNEL == :Darwin
    buildcmd = `make lib LIBRARY_PATH=$lib CPATH=$inc CXX=g++-8 CC=gcc-8 DYNAMICLIB=lib/libfinufft.dylib`
else
    buildcmd = `make lib LIBRARY_PATH=$lib CPATH=$inc`
end
```

Unfortunately it is not possible to do `brew install gcc` on travis osx image. I did not understand.

**Comment by pnavaro** [comment]
Here a workaround for this error on OSX
~~~
Undefined symbols for architecture x86_64:
│   "_GOMP_parallel", referenced from:
│       spreadwithsortidx(
~~~
i modified the line 54 in deps/build.jl
buildcmd = `make lib/libfinufft.so LIBRARY_PATH=$lib CPATH=$inc FFTWOMPS    UFFIX=threads CXX=g++-8 CC=gcc-8 OMPLIBS=/usr/local/lib/libgomp.a`

Not sure it will work on travis ...

**Comment by ludvigak** [comment]
That's good to know, but I'm hesitant to add that since it hardcodes the path into the build script. For now everything is working fine on Travis at least, which has to be my baseline since I don't have a Mac of my own.

**Comment by pnavaro** [comment]
I understand, it is not easy to build the low level library on all platform with BinDeps. Perhaps on day there is a homebrew or a conda package for the finufft c library.

**Comment by ludvigak** [comment]
The ideal solution would be to use BinaryBuilder to provide a working binaries for all platforms. I'm playing around with that currently...
