### ISSUE TITLE
ComplexF32 data support

### ISSUE THREAD

**Issue by y9KAaixxegjR** [ludvigak/FINUFFT.jl#22]
First, thank you for this submission! The code works really, really well, and especially shines in 3D. This is a feature request: 

Storing big 3D volumes as `ComplexF64` is very memory intensive. Does the core C++ code support complex floats instead of doubles? If so, wrapping the `ComplexF32` variant would be very useful for large 3D problems.

**Comment by ludvigak** [comment]
Hi! Glad to hear you find the code useful.

The underlying library FINUFFT does indeed have single-precision support, but that has not been added to this interface yet. There's no timeplan available for it either, but contributions are of course welcome =)

**Comment by ludvigak** [comment]
Hey @y9KAaixxegjR , I have now implemented interfaces to the 32-bit calls of the library. Let me know if you encounter any issues with them.
