### ISSUE TITLE
nufft1d2 not working

### ISSUE THREAD

**Issue by erny123** [ludvigak/FINUFFT.jl#51]
the type 1 transform works. 

However, I can't even get this to work: 

`FINUFFT.nufft1d2(xj=[-2.0, -1.0, 0.0, 0.5, 3.0], fk = [1.0im, 1.0im, 1.0im, 1.0im])`

With error:

```
MethodError: no method matching nufft1d2(; xj::Vector{Float64}, fk::Vector{ComplexF64})

Closest candidates are:

nufft1d2(!Matched::Array{T}, !Matched::Integer, !Matched::Real, !Matched::Array{Complex{T}}; kwargs...) where T<:Union{Float32, Float64}

@ FINUFFT ~/.julia/packages/FINUFFT/Tq5pq/src/simple.jl:189
```

The error indicates that every input matches. So what's the issue?

**Comment by ludvigak** [comment]
Hi,
I'm afraid it says that none of the inputs match. If you look att the [docs](https://ludvigak.github.io/FINUFFT.jl/latest/#FINUFFT.nufft1d2-Union{Tuple{T},%20Tuple{Array{T},%20Integer,%20Real,%20Array{Complex{T}}}}%20where%20T%3C:Union{Float32,%20Float64}) you see that nufft1d2 takes 4 four arguments, and none of them are keyword arguments.

e.g.
```julia
julia> FINUFFT.nufft1d2([-2.0, -1.0, 0.0, 0.5, 3.0], 1, 1e-15, [1.0im, 1.0im, 1.0im, 1.0im])
5×1 Matrix{ComplexF64}:
     0.7568024953079283 - 0.4859372939578959im
    -0.9092974268256819 + 1.664457775189138im
 1.0027984050638022e-16 + 4.000000000000003im
     0.8414709848078963 + 3.295467429648886im
    -0.2794154981989256 - 0.019814706550525238im
```
