### ISSUE TITLE
Possible sub-optimal flags in cmake 

### ISSUE THREAD

**Issue by DiamonDinoia** [ludvigak/FINUFFT.jl#55]
The flags used in https://github.com/JuliaPackaging/Yggdrasil/blob/dbe6fe9649dc72119f1bc3f39f8a14e1c0552fd6/F/finufft/build_tarballs.jl#L24 mean:
1. Use FFTW in the system first 
2. do not enable fftw OpenMP

The package relies on fftw julia package which builds with ptreads. Is there an issue with omp and Julia?

One can do:
 - `-DFINUFFT_FFTW_LIBRARIES=DOWNLOAD` then finufft downloads, builds and static links fftw.
 - set build type to release (-O3)

preferred gcc version: refer to https://github.com/flatironinstitute/finufft/discussions/452

**Comment by ludvigak** [comment]
CMake build type Release made a 5x difference in my tests, new build for that is on the way: https://github.com/JuliaPackaging/Yggdrasil/pull/8956

Did not see much difference in rudimentary tests from changing gcc version and FFTW parallelization. Will not change for now, but may revisit after ongoing round of FINUFFT optimizations have been released.
